// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelHashing(arg1) {
  return window['go']['main']['App']['CancelHashing'](arg1);
}

export function ChooseFiles() {
  return window['go']['main']['App']['ChooseFiles']();
}

export function ChooseOpenPath(arg1) {
  return window['go']['main']['App']['ChooseOpenPath'](arg1);
}

export function ChooseSavePath(arg1, arg2) {
  return window['go']['main']['App']['ChooseSavePath'](arg1, arg2);
}

export function ClearIdentity() {
  return window['go']['main']['App']['ClearIdentity']();
}

export function DeleteRecord(arg1) {
  return window['go']['main']['App']['DeleteRecord'](arg1);
}

export function DescribeFiles(arg1) {
  return window['go']['main']['App']['DescribeFiles'](arg1);
}

export function ExportAnchorResult(arg1, arg2) {
  return window['go']['main']['App']['ExportAnchorResult'](arg1, arg2);
}

export function ExportGlobalProof(arg1, arg2) {
  return window['go']['main']['App']['ExportGlobalProof'](arg1, arg2);
}

export function ExportPrivateKey() {
  return window['go']['main']['App']['ExportPrivateKey']();
}

export function ExportProofBundle(arg1, arg2) {
  return window['go']['main']['App']['ExportProofBundle'](arg1, arg2);
}

export function ExportSingleProof(arg1, arg2) {
  return window['go']['main']['App']['ExportSingleProof'](arg1, arg2);
}

export function GenerateIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateIdentity'](arg1, arg2, arg3);
}

export function GetIdentity() {
  return window['go']['main']['App']['GetIdentity']();
}

export function GetAnchorSystemResource(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAnchorSystemResource'](arg1, arg2, arg3);
}

export function GetAnchorSystemStatus(arg1) {
  return window['go']['main']['App']['GetAnchorSystemStatus'](arg1);
}

export function GetProofBundle(arg1) {
  return window['go']['main']['App']['GetProofBundle'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportIdentity(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportIdentity'](arg1, arg2, arg3, arg4);
}

export function LatestRoot() {
  return window['go']['main']['App']['LatestRoot']();
}

export function ListRecords() {
  return window['go']['main']['App']['ListRecords']();
}

export function ListAnchorSystems() {
  return window['go']['main']['App']['ListAnchorSystems']();
}

export function ListAnchorSystemResources(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListAnchorSystemResources'](arg1, arg2, arg3, arg4);
}

export function ListRecordsPage(arg1) {
  return window['go']['main']['App']['ListRecordsPage'](arg1);
}

export function ListRemoteRecordsPage(arg1) {
  return window['go']['main']['App']['ListRemoteRecordsPage'](arg1);
}

export function ListRoots(arg1) {
  return window['go']['main']['App']['ListRoots'](arg1);
}

export function RefreshRecord(arg1) {
  return window['go']['main']['App']['RefreshRecord'](arg1);
}

export function RotateIdentity(arg1) {
  return window['go']['main']['App']['RotateIdentity'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ServerHealth() {
  return window['go']['main']['App']['ServerHealth']();
}

export function ServerMetrics() {
  return window['go']['main']['App']['ServerMetrics']();
}

export function StartHashing(arg1) {
  return window['go']['main']['App']['StartHashing'](arg1);
}

export function SubmitBatch(arg1) {
  return window['go']['main']['App']['SubmitBatch'](arg1);
}

export function SubmitFile(arg1) {
  return window['go']['main']['App']['SubmitFile'](arg1);
}

export function UpgradeOtsAnchor(arg1) {
  return window['go']['main']['App']['UpgradeOtsAnchor'](arg1);
}

export function VerifyProof(arg1) {
  return window['go']['main']['App']['VerifyProof'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
