// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';
import {anchor} from '../models';

export function CancelHashing(arg1:string):Promise<boolean>;

export function ChooseFiles():Promise<Array<string>>;

export function ChooseOpenPath(arg1:string):Promise<string>;

export function ChooseSavePath(arg1:string,arg2:string):Promise<string>;

export function ClearIdentity():Promise<void>;

export function DeleteRecord(arg1:string):Promise<void>;

export function DescribeFiles(arg1:Array<string>):Promise<Array<main.FileInfo>>;

export function ExportAnchorResult(arg1:string,arg2:string):Promise<void>;

export function ExportGlobalProof(arg1:string,arg2:string):Promise<void>;

export function ExportPrivateKey():Promise<string>;

export function ExportProofBundle(arg1:string,arg2:string):Promise<void>;

export function ExportSingleProof(arg1:string,arg2:string):Promise<void>;

export function GenerateIdentity(arg1:string,arg2:string,arg3:string):Promise<main.IdentityView>;

export function GetIdentity():Promise<main.IdentityView>;

export function GetAnchorSystemResource(arg1:string,arg2:string,arg3:string):Promise<model.AnchorSystemResource>;

export function GetAnchorSystemStatus(arg1:string):Promise<model.AnchorSystemStatus>;

export function GetProofBundle(arg1:string):Promise<model.ProofBundle>;

export function GetSettings():Promise<main.Settings>;

export function ImportIdentity(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.IdentityView>;

export function LatestRoot():Promise<model.BatchRoot>;

export function ListRecords():Promise<Array<main.LocalRecord>>;

export function ListAnchorSystems():Promise<Array<model.AnchorSystem>>;

export function ListAnchorSystemResources(arg1:string,arg2:string,arg3:number,arg4:string):Promise<model.AnchorSystemResourcePage>;

export function ListRecordsPage(arg1:main.RecordPageOptions):Promise<main.RecordPage>;

export function ListRemoteRecordsPage(arg1:main.RecordPageOptions):Promise<main.RecordPage>;

export function ListRoots(arg1:number):Promise<Array<model.BatchRoot>>;

export function RefreshRecord(arg1:string):Promise<main.LocalRecord>;

export function RotateIdentity(arg1:string):Promise<main.IdentityView>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function ServerHealth():Promise<main.HealthStatus>;

export function ServerMetrics():Promise<Array<main.Metric>>;

export function StartHashing(arg1:Array<string>):Promise<string>;

export function SubmitBatch(arg1:Array<main.SubmitRequest>):Promise<Array<main.BatchItemResult>>;

export function SubmitFile(arg1:main.SubmitRequest):Promise<main.SubmitResult>;

export function UpgradeOtsAnchor(arg1:string):Promise<anchor.OtsUpgradeSummary>;

export function VerifyProof(arg1:main.VerifyRequest):Promise<main.VerifyResponse>;

export function Version():Promise<string>;
