export const fr = {
  lang: "fr",
  ui: {
    docs: "Documentation",
    home: "Accueil de la documentation",
    updated: "Mis à jour le 22/07/2026",
    version: "Pour TrustDB 1.0.0",
    duration: "Durée estimée",
    outcome: "À la fin, vous aurez",
    prerequisites: "Avant de commencer",
    expected: "Résultat attendu",
    checkpoint: "Point de contrôle",
    next: "Étape suivante",
  },
  nav: {
    groups: [
      ["Démarrer", [
        ["Accueil de la documentation", "/docs"],
        ["Comprendre TrustDB", "/docs/concepts"],
        ["Démarrage rapide en 10 minutes", "/docs/quick-start"],
      ]],
      ["Intégrer", [
        ["Tutoriel du SDK Go", "/docs/sdk"],
        ["Entrée NATS / JetStream", "/docs/nats-ingress"],
        ["Vérification hors ligne", "/docs/offline-verification"],
        ["Référence CLI", "/docs/cli"],
        ["Client de bureau", "/docs/desktop"],
      ]],
      ["Exploiter", [
        ["Déploiement en production", "/docs/server"],
        ["Dépannage", "/docs/troubleshooting"],
      ]],
      ["Référence", [
        ["Installer le client de bureau", "/docs/desktop-install"],
        ["Compiler depuis les sources", "/docs/source-build"],
        [".sproof v1", "/sproof"],
        ["Référence de performances", "/performance"],
      ]],
    ],
  },
  index: {
    eyebrow: "Documentation",
    title: ["Partez de zéro.", "Livrez des preuves vérifiables."],
    lead: "Obtenez une preuve L3 vérifiée localement en dix minutes, puis passez au SDK Go, au déploiement en production ou à la vérification d’un .sproof côté destinataire. Chaque parcours fournit les prérequis, des commandes à copier, le résultat attendu et des pistes en cas d’échec.",
    meta: "Parcours de prise en main TrustDB · v1.0.0",
    primary: "Commencer le tutoriel de 10 minutes",
    secondary: "Comprendre d’abord le modèle de preuve",
    chooseEyebrow: "Choisissez votre objectif",
    chooseTitle: ["Plus besoin de deviner l’ordre.", "Commencez par votre objectif."],
    chooseLead: "Six parcours partagent exactement la même sémantique de preuve. Évaluez TrustDB localement, intégrez-le à votre application, puis exploitez-le en toute sécurité.",
    paths: [
      ["10 MIN", "L’exécuter localement", "Créez un ProofBundle L3 depuis un dossier vide et vérifiez que le fichier source n’a pas été modifié.", "/docs/quick-start", "Produit example.tdproof"],
      ["BUILD", "Intégrer le SDK Go", "Démarrez un serveur local, soumettez un fichier, attendez L4, exportez .sproof et vérifiez-le localement.", "/docs/sdk", "Produit un exemple exécutable et record.sproof"],
      ["STREAM", "Ajouter l’entrée NATS", "Regroupez durablement les claims signés via JetStream et récupérez le résultat L2 immuable après délai ou redémarrage.", "/docs/nats-ingress", "Produit un chemin broker borné et des règles de reprise"],
      ["VERIFY", "Vérifier une preuve reçue", "Recalculez la preuve avec des clés de confiance obtenues indépendamment, sans service ni réseau disponibles.", "/docs/offline-verification", "Produit un résultat de vérification hors ligne"],
      ["OPERATE", "Déployer en production", "Planifiez les données persistantes, les limites des clés, la protection réseau, les contrôles d’état, la sauvegarde et un exercice de restauration.", "/docs/server", "Produit une checklist de mise en production"],
      ["RECOVER", "Résoudre les incidents courants", "Diagnostiquez par symptôme les permissions, les clés, la disponibilité des preuves, l’ancrage, les verrous Pebble et les erreurs de schéma.", "/docs/troubleshooting", "Produit des étapes de reprise sûres"],
    ],
    modelEyebrow: "Parcours d’apprentissage",
    modelTitle: ["Comprenez. Testez.", "Puis passez en production."],
    modelSteps: [
      ["01", "Comprendre", "Découvrez ce que TrustDB prouve, ce qu’il ne prouve pas et comment L1–L5 ajoutent progressivement des éléments vérifiables indépendamment."],
      ["02", "Expérimenter", "Utilisez la CLI pour créer des clés, une déclaration et une preuve L3, puis observez une réussite et un échec après altération."],
      ["03", "Intégrer", "Utilisez le SDK Go pour signer et traiter les preuves ; ajoutez l’entrée NATS / JetStream facultative pour un regroupement durable."],
      ["04", "Exploiter", "Figez les versions et la configuration, séparez les racines de confiance, protégez la périphérie réseau et répétez la restauration."],
    ],
    boundaryTitle: "Le fichier source peut rester hors de TrustDB, et la vérification n’exige pas que TrustDB soit en ligne.",
    boundaryBody: "Le service central reçoit un condensat signé et les métadonnées choisies, puis produit les reçus et les preuves. Les vérificateurs doivent obtenir les clés publiques du client et du serveur par des canaux de confiance ; les données incluses dans le fichier de preuve ne deviennent pas, à elles seules, une racine de confiance.",
  },
  quickStart: {
    title: "Démarrage rapide en 10 minutes",
    lead: "Depuis un dossier vide, réalisez une signature locale, un commit Merkle L3, une vérification indépendante et un test négatif après altération. Aucun serveur ni outil Go n’est nécessaire.",
    duration: "10 minutes",
    outcome: "example.tdproof et un résultat L3 valide recalculé",
    prerequisites: ["Un terminal macOS ou Linux (sous Windows, utilisez le ZIP correspondant et PowerShell)", "curl, tar, grep et shasum/sha256sum", "Un nouveau dossier d’exercice ; ne réutilisez jamais un dossier de clés de production"],
    downloadTitle: "1. Télécharger puis vérifier l’archive",
    downloadBody: "Téléchargez l’archive de la version et le manifeste des sommes de contrôle. Vérifiez l’archive avant de l’extraire ; cet exemple utilise un Mac Apple Silicon.",
    downloadExpected: "La commande de contrôle affiche le nom de l’archive suivi de OK. En cas de différence, arrêtez-vous et téléchargez de nouveau depuis GitHub Releases.",
    allPlatforms: "Choisir une autre plateforme",
    platformNoteTitle: "Linux et Windows",
    platformNoteBody: "Sous Linux, utilisez sha256sum -c. Sous Windows, téléchargez le ZIP correspondant et SHA256SUMS, comparez le résultat de Get-FileHash -Algorithm SHA256, puis extrayez l’archive et utilisez .\\bin\\trustdb.exe dans PowerShell pour les commandes suivantes.",
    linuxPathLabel: "Linux amd64 : télécharger, vérifier et extraire",
    windowsPathLabel: "Windows x86-64 : tutoriel PowerShell complet",
    extractTitle: "2. Extraire et créer le fichier d’exercice",
    extractBody: "Entrez dans le dossier de la version et créez explicitement le fichier d’entrée. Tous les états jetables restent sous .trustdb-dev.",
    extractExpected: "version affiche 1.0.0 et example.txt contient hello TrustDB.",
    keysTitle: "3. Générer des clés client et serveur à usage unique",
    keysBody: "La clé privée du client signe le condensat du contenu ; la clé privée du serveur signe les reçus. Les clés publiques servent à la vérification.",
    keysWarning: "key generate remplace les fichiers de clés de même nom. Exécutez-le une seule fois dans un nouveau dossier d’exercice ; ne le relancez jamais pour une identité ayant déjà émis des preuves.",
    keysExpected: ".trustdb-dev contient client.key, client.pub, server.key et server.pub. Ne transmettez jamais les clés privées à un vérificateur.",
    claimTitle: "4. Créer localement une déclaration signée",
    claimBody: "La CLI lit example.txt en flux, calcule son condensat et crée un .tdclaim. Le fichier source n’est pas téléversé.",
    claimExpected: ".trustdb-dev/example.tdclaim existe et example.txt reste local.",
    commitTitle: "5. Effectuer un commit dans un lot Merkle local",
    commitBody: "Le commit local utilise un WAL d’exercice dédié et crée un ProofBundle L3. Il ne soumet rien à un serveur TrustDB en cours d’exécution.",
    commitExpected: ".trustdb-dev/example.tdproof existe ; proof inspect affiche record_id, batch_id et tree_size.",
    verifyTitle: "6. Vérifier indépendamment",
    verifyBody: "Le vérificateur recalcule le condensat du fichier, la signature du client, le reçu du serveur et le chemin Merkle, sans faire confiance à un niveau de preuve déclaré.",
    verifyExpected: "La commande se termine avec le code 0 et le JSON contient \"valid\":true et \"proof_level\":\"L3\".",
    tamperTitle: "7. Confirmer qu’une altération échoue",
    tamperBody: "Copiez le fichier source, ajoutez une ligne, puis vérifiez-le avec la même preuve. Cette commande doit se terminer avec un code non nul.",
    tamperExpected: "La vérification échoue. La preuve ne correspond qu’au fichier example.txt original ; supprimer tampered.txt ne modifie pas la preuve.",
    nextTitle: "Étape suivante : connecter la même chaîne de preuve à un service",
    nextBody: "Cette page s’arrête à L3 local. Poursuivez avec le tutoriel du SDK Go pour l’ingestion partagée, les lots asynchrones, le Global Log L4 et l’ancrage externe L5 facultatif.",
  },
  sdk: {
    title: "SDK Go : soumettre, attendre, exporter, vérifier",
    lead: "Exécutez un exemple complet et compilable qui contrôle l’état du service, soumet un fichier, attend L4, écrit un .sproof et le vérifie uniquement avec le fichier source et les clés de confiance locales.",
    duration: "20 à 30 minutes",
    outcome: "Un record_id, un record.sproof de niveau L4 ou supérieur et un résultat de vérification locale",
    prerequisites: ["Avoir terminé le démarrage rapide de 10 minutes et conservé example.txt ainsi que les clés .trustdb-dev", "Go 1.26.5 ou une version compatible", "Deux terminaux ; le service écoute uniquement sur 127.0.0.1"],
    serverTitle: "1. Démarrer un serveur local avec des chemins relatifs",
    serverBody: "Cette commande ne charge pas production.yaml ; tous les états modifiables restent dans le dossier d’exercice. Le Global Log est activé, donc un enregistrement passe de façon asynchrone de L2 à L3, puis à L4.",
    serverExpected: "healthz indique que le service est sain ; laissez ce terminal en cours d’exécution.",
    projectTitle: "2. Créer un dossier isolé pour l’exemple SDK",
    projectBody: "Créez un module Go distinct sous .trustdb-dev. L’exemple lit, via des chemins relatifs, le fichier et les clés laissés par le démarrage rapide. Figez v1.0.0 plutôt qu’une dépendance flottante.",
    projectExpected: "go.mod fixe github.com/wowtrust/trustdb v1.0.0 ; example.txt et les trois clés requises restent à leur emplacement d’exercice d’origine.",
    codeTitle: "3. Exécuter l’exemple complet vérifié par compilation",
    codeBody: "Dépliez le code source complet ci-dessous, copiez-le et enregistrez-le sous main.go dans le répertoire courant. examples/sdk-onboarding/main.go est la source canonique de cette page et sa compilation est couverte par les tests Go. Il interroge avec un délai maximal et ne présente jamais la réponse L2 initiale comme L4.",
    codeExpected: "La sortie contient d’abord submitted record_id=… proof_level=L2 dans le cas habituel, puis verified record_id=… proof_level=L4. record.sproof est créé.",
    sourceLabel: "Voir le code source de l’exemple vérifié par compilation",
    asyncTitle: "Pourquoi l’exemple attend",
    asyncBody: "SubmitFile renvoie à la frontière d’acceptation L2. La clôture du lot et la matérialisation Merkle ajoutent L3, la publication dans le Global Log ajoute L4, et un résultat d’ancrage réussi d’un sink pris en charge qui correspond exactement ajoute L5. Seul un fournisseur réellement externe confère une sémantique temporelle externe ; noop/file ne le font pas. L’exemple attend un GlobalProof non nul et échoue clairement à l’expiration du délai.",
    idempotencyTitle: "Ne reconstruisez pas une déclaration lors des nouvelles tentatives en production",
    idempotencyBody: "L’exemple rapide laisse le SDK générer une clé d’idempotence aléatoire. Pour des tentatives de production sûres, appelez BuildSignedFileClaim une seule fois et soumettez de nouveau le même SignedClaim après une erreur réseau. Une reconstruction modifie produced_at/nonce et ne peut pas être associée à la même clé d’idempotence.",
    offlineTitle: "4. Arrêter le service, puis vérifier de nouveau",
    offlineBody: "Appuyez sur Ctrl+C dans le terminal du serveur, puis lancez la CLI. Cette opération n’accède ni à TrustDB, ni à un fournisseur d’ancrage, ni au réseau.",
    offlineExpected: "La vérification renvoie toujours valid=true lorsque le service est arrêté ; le niveau est recalculé à partir des éléments valides présents dans le fichier.",
  },
  offline: {
    title: "Vérifier .sproof entièrement hors ligne",
    lead: "Placez-vous côté destinataire : contrôlez la livraison, obtenez les racines de confiance indépendamment et recalculez la preuve lorsque TrustDB et le réseau sont indisponibles.",
    duration: "5 à 10 minutes",
    outcome: "Un résultat L3, L4 ou L5 recalculé indépendamment, plus un échec d’altération consigné",
    prerequisites: ["Le fichier source, par exemple example.txt", "Sa preuve monofichier, par exemple record.sproof", "Les clés publiques du client et du serveur obtenues séparément par des canaux de confiance", "Une CLI TrustDB locale ; déconnectez le réseau et arrêtez le service pendant la vérification"],
    packageTitle: "1. Contrôler le paquet livré",
    packageBody: ".sproof embarque le ProofBundle et peut contenir le GlobalLogProof et l’AnchorResult qui lui correspondent exactement. Il n’interroge pas le serveur pour compléter des éléments manquants.",
    trustTitle: "Une preuve ne peut pas désigner ses propres racines de confiance",
    trustBody: "Ne faites pas confiance à des clés uniquement parce qu’elles apparaissent dans ou à côté de .sproof. Figez les clés publiques du client et du serveur à l’aide d’une annexe contractuelle, d’une configuration contrôlée, d’une empreinte vérifiée hors ligne ou d’un autre canal indépendant.",
    verifyTitle: "2. Vérifier avec le réseau déconnecté",
    verifyBody: "Le vérificateur relit le fichier source et contrôle chaque couche. Le niveau affiché provient uniquement des vérifications effectivement réussies.",
    verifyExpected: "valid=true. Un ProofBundle seul est plafonné à L3 ; un GlobalLogProof valide donne L4. L5 exige une correspondance exacte de TreeSize et RootHash ; NodeID/LogID doivent correspondre lorsque les deux côtés les fournissent ; le sink pris en charge et l’anchor_id déterministe sont vérifiés, et une preuve OTS fait en plus l’objet d’une validation de structure et de condensat.",
    levelTitle: "3. Interpréter correctement le niveau",
    levels: [
      ["L3", "Le fichier source, la signature, le reçu serveur et le chemin Merkle du lot sont valides.", "Ne prouve pas encore l’inclusion dans le Global Log."],
      ["L4", "Le lot est inclus dans le Global Log couvert par le Signed Tree Head embarqué.", "N’implique pas l’existence d’un ancrage temporel externe."],
      ["L5", "TreeSize et RootHash correspondent exactement au STH ; les champs d’identité non vides, l’enveloppe du sink et l’anchor_id sont validés, avec des contrôles supplémentaires de la preuve OTS.", "noop/file peuvent produire L5, mais ne fournissent pas de temps externe indépendant."],
    ],
    skipTitle: "Limiter l’évaluation à L4",
    skipBody: "--skip-anchor ignore les éléments L5 disponibles et rapporte L4 lorsque le Global Proof est valide. Il ne promeut pas un enregistrement serveur L2/L3 en L4.",
    tamperTitle: "4. Effectuer un test négatif d’altération",
    tamperBody: "Modifier le fichier source, le chemin Merkle, la signature STH, la root, l’anchor_id ou les champs OTS vérifiés (TreeSize, algorithme et digest de hachage, horodatage d’acceptation) doit faire échouer la vérification. Le champ Proof de file/noop et les métadonnées de diagnostic OTS, telles que l’heure de soumission, l’URL du calendrier ou le code d’état, ne portent pas de sémantique de sécurité ; ne fondez donc pas un test d’altération sur la seule modification de ces champs. Commencez par le fichier source.",
    tamperExpected: "La commande se termine avec un code non nul. La vérification réussit de nouveau lorsque le fichier source original et record.sproof sont restaurés.",
  },
  server: {
    title: "Déploiement en production et restauration",
    lead: "Commencez par un nœud local sûr, puis rendez explicites les chemins binaire/Docker, le stockage persistant, les limites des clés, la protection réseau, les contrôles d’état, la sauvegarde et la restauration.",
    duration: "30 à 60 minutes, plus un exercice de restauration",
    outcome: "Un déploiement TrustDB mononœud supervisé, sauvegardé et restaurable, avec des limites explicites",
    prerequisites: ["Avoir terminé le démarrage rapide de 10 minutes et conservé les fichiers d’exercice .trustdb-dev/server.key et client.pub", "Une version TrustDB figée et son SHA-256 vérifié", "Le choix entre un déploiement binaire ou Docker", "Des emplacements planifiés pour les données persistantes, les journaux, les clés, le key registry et les sauvegardes", "Un plan de reverse proxy, mTLS ou politique réseau ; n’exposez jamais une API d’écriture non protégée sur l’Internet public"],
    localTitle: "1. Commencer par un test rapide avec des chemins relatifs",
    localBody: "Cette commande fonctionne depuis une archive de version avec un utilisateur non root. Elle localise explicitement le WAL, Pebble et les données de preuve, afin d’éviter toute écriture accidentelle dans /var/lib ou /var/log.",
    localExpected: "healthz réussit, records renvoie une page et metrics renvoie du texte Prometheus.",
    dockerTitle: "2. Déploiement Docker rapide",
    dockerBody: "Le volume nommé conserve l’état et les clés générées au premier démarrage. Sans ce volume, supprimer le conteneur supprime son identité et son état de preuve.",
    dockerExpected: "Le conteneur est healthy/running, les journaux signalent la génération initiale des clés et healthz réussit.",
    dockerBoundary: "Par commodité, Docker conserve la clé privée du client de démonstration avec l’état du serveur. En production, gardez les clés privées client dans l’application métier et ne configurez sur le serveur que la clé publique correspondante ou un registre de confiance.",
    templateTitle: "3. Passer ensuite à production.yaml",
    templateBody: "L’archive de version utilise config/production.yaml ; l’arborescence source utilise configs/production.yaml. Les valeurs par défaut ciblent /etc/trustdb, /var/lib/trustdb et /var/log/trustdb. Créez les dossiers, appliquez le moindre privilège et remplacez d’abord les chemins de clés. run_profile n’est qu’un libellé d’observabilité et --data-dir ne déplace pas automatiquement le WAL, le proofstore, les journaux et les clés.",
    templatesLabel: "Voir les modèles de configuration",
    profilesTitle: "Choisir le stockage et la durabilité",
    profiles: [
      ["file", "Une organisation légère pour le développement, qui n’est pas la référence de production à haut débit."],
      ["Pebble", "Le proofstore de production mononœud recommandé ; le service en cours d’exécution détient le verrou de son dossier."],
      ["TiKV", "Les nœuds de calcul peuvent partager un cluster TiKV, mais un namespace de proofstore appartient à un seul flux logique (node_id, log_id) ; les écritures actives-actives dans un même namespace ne sont pas prises en charge."],
      ["fsync", "Les modes valides sont strict, group et batch ; préférez group par défaut en production. benchmark-extreme.yaml est un profil de benchmark, pas un mode fsync."],
    ],
    anchorTitle: "Limite de l’ancrage",
    anchorBody: "Docker utilise par défaut le sink noop, qui teste l’ordonnancement et le flux de preuve mais ne fournit pas de temps externe indépendant. Pour une sémantique temporelle externe L5, configurez un fournisseur pris en charge et exigez un résultat immuable qui corresponde exactement au Signed Tree Head de la preuve.",
    securityTitle: "Réseau et contrôle d’accès",
    securityBody: "Les API HTTP/gRPC métier de TrustDB ne remplacent pas TLS, l’identité ou l’autorisation par tenant. Exécutez TrustDB dans un réseau contrôlé et protégez l’entrée par un reverse proxy, mTLS, une API gateway, un pare-feu ou une politique réseau. Admin Web est désactivé par défaut ; s’il est activé, configurez des identifiants, un session secret et des cookies HTTPS sécurisés.",
    backupTitle: "4. Arrêter le service, puis créer et vérifier une sauvegarde logique",
    backupBody: "Pebble ne peut pas être ouvert simultanément par le service et le processus de sauvegarde. Arrêtez proprement les écritures, puis créez et vérifiez la sauvegarde avant de la restaurer dans un nouveau chemin. N’écrasez jamais le dossier original lors du premier exercice.",
    backupBoundary: ".tdbackup ne contient que l’état de preuve du proofstore : bundles, roots, Global Log, STH, résultats d’ancrage et état du scheduler. Il exclut le WAL, les checkpoints WAL, la configuration, les clés privées, les fichiers sources, le key registry et les éléments de confiance du registry. Sauvegardez-les séparément au même point de reprise ; n’associez un proofstore restauré qu’à son WAL et son registry correspondants, jamais à un ancien état arbitraire.",
    checklistTitle: "Checklist de mise en production",
    checklist: ["Figer un digest d’image ou une version de release et conserver le SHA-256", "Séparer les clés privées client et serveur ; distribuer les clés publiques par des canaux contrôlés", "Superviser la capacité et les permissions de chaque chemin persistant et de journalisation", "N’exposer les écritures que derrière un réseau protégé ou une entrée TLS/mTLS", "Confirmer la sémantique réelle du sink d’ancrage ; ne jamais traiter noop comme une source de temps externe", "Vérifier healthz, records, metrics et l’arrêt propre", "Effectuer service arrêté un backup, backup verify et une restauration dans un chemin indépendant", "Lire les release notes avant toute mise à niveau et valider le schéma et les preuves sur une copie"],
    apiTitle: "API de lecture et d’intégration",
    apiBody: "Les écritures HTTP utilisent du CBOR déterministe, pas du JSON écrit à la main ; gRPC utilise le codec CBOR déterministe du projet. Préférez le SDK Go ou le client de bureau pour les écritures métier. curl convient aux contrôles d’état et aux diagnostics en lecture seule.",
  },
  troubleshooting: {
    title: "Dépannage",
    lead: "Partez du symptôme et suivez le chemin de diagnostic le plus court. Chaque correction préserve les clés, le WAL, le proofstore et les preuves, au lieu de masquer l’erreur en supprimant l’état.",
    duration: "2 à 10 minutes par cas",
    outcome: "Une cause identifiée, un diagnostic exécutable et une étape suivante qui respecte les limites de preuve",
    introTitle: "Préserver d’abord l’état des lieux",
    introBody: "Notez la version, l’erreur complète, les arguments de démarrage et les permissions des chemins. Ne relancez pas key generate, ne supprimez pas Pebble/WAL, n’écrasez pas les sauvegardes et ne publiez pas de clés privées dans une issue publique.",
    diagnosticsTitle: "Diagnostics courants",
    causeLabel: "Cause probable",
    actionLabel: "Étape suivante sûre",
    cards: [
      ["permission denied / cannot create log", "production.yaml pointe vers /var/lib, /var/log ou /etc sans permissions suffisantes.", "En local, utilisez les chemins relatifs explicites du tutoriel. En production, créez un utilisateur et des dossiers dédiés, puis définissez précisément owner/mode. Ne créez pas une partie de l’état avec sudo avant de continuer sous un autre utilisateur."],
      ["signature verification failed / key mismatch", "Le fichier source a changé, le vérificateur possède une mauvaise clé client/serveur, ou key generate a remplacé une identité ayant déjà émis des preuves.", "Comparez le condensat source et les empreintes conservées par des canaux de confiance. Préservez les fichiers actuels ; générer de nouvelles clés ne peut pas réparer une preuve historique."],
      ["proof not found / still L2", "La déclaration a été acceptée, mais la clôture du lot ou la matérialisation de la preuve n’est pas terminée.", "Relancez GetProofBundle/ExportSingleProof avec un backoff borné. L2 n’est pas un échec ; ne bouclez jamais sans délai maximal."],
      ["server verification requires L4", "trustdb verify --server récupère la preuve du Global Log, qu’un enregistrement L2/L3 ne peut pas encore satisfaire.", "Attendez L4 ou vérifiez un ProofBundle L3 déjà exporté. --skip-anchor ignore uniquement L5 ; il ne transforme pas L3 en L4."],
      ["L5 never appears", "L’ancrage est désactivé, la fenêtre fixe n’a pas encore expiré, ou la publication par le fournisseur a échoué et fait l’objet de nouvelles tentatives.", "Vérifiez la configuration de l’ancrage, le sink, max_delay, le scheduler et les journaux du fournisseur. Les résultats noop/file réussis produisent eux aussi L5, mais pas de temps externe indépendant. L’acceptation initiale par le calendrier OTS produit L5 ; les mises à niveau ultérieures ne font qu’enrichir sa preuve. Ne modifiez jamais proof_level manuellement."],
      ["resource temporarily unavailable / LOCK", "Le service en cours détient le dossier Pebble, donc aucun autre processus de sauvegarde ou serveur ne peut l’ouvrir.", "Arrêtez proprement le service, confirmez sa fin, puis exécutez backup create. Restaurez dans un nouveau dossier cible."],
      ["schema/version mismatch", "Le binaire refuse un store ou une sauvegarde dont la version de schéma/format diffère.", "Conservez l’original et identifiez la version de TrustDB qui l’a créé. Suivez une migration prise en charge ou utilisez d’abord la version correspondante pour exporter ; ne supprimez jamais les marqueurs de version et n’ajoutez pas de compatibilité en double lecture."],
    ],
    askTitle: "Toujours bloqué ?",
    askBody: "Ouvrez une issue GitHub en indiquant la version de TrustDB, le système d’exploitation, les étapes de reproduction, les champs de configuration expurgés, l’erreur complète et les diagnostics déjà exécutés. Ne publiez jamais de véritables clés privées, tokens, adresses de production, données client ou preuves non expurgées.",
    openIssueLabel: "Ouvrir une issue",
  },
};

export const ko = {
  lang: "ko",
  ui: {
    docs: "문서",
    home: "문서 홈",
    updated: "2026-07-22 업데이트",
    version: "TrustDB 1.0.0 기준",
    duration: "예상 소요 시간",
    outcome: "완료 후 결과",
    prerequisites: "시작하기 전에",
    expected: "예상 결과",
    checkpoint: "확인 지점",
    next: "다음 단계",
  },
  nav: {
    groups: [
      ["시작", [
        ["문서 홈", "/docs"],
        ["TrustDB 이해하기", "/docs/concepts"],
        ["10분 빠른 시작", "/docs/quick-start"],
      ]],
      ["연동", [
        ["Go SDK 튜토리얼", "/docs/sdk"],
        ["NATS / JetStream ingress", "/docs/nats-ingress"],
        ["오프라인 검증", "/docs/offline-verification"],
        ["CLI 레퍼런스", "/docs/cli"],
        ["데스크톱 클라이언트", "/docs/desktop"],
      ]],
      ["운영", [
        ["프로덕션 배포", "/docs/server"],
        ["문제 해결", "/docs/troubleshooting"],
      ]],
      ["참조", [
        ["데스크톱 클라이언트 설치", "/docs/desktop-install"],
        ["소스에서 빌드", "/docs/source-build"],
        [".sproof v1", "/sproof"],
        ["성능 기준", "/performance"],
      ]],
    ],
  },
  index: {
    eyebrow: "문서",
    title: ["처음부터 시작해", "검증 가능한 증거를 전달하세요."],
    lead: "10분 안에 로컬에서 검증된 L3 증명을 만든 뒤 Go SDK, 프로덕션 배포, 수신자 측 .sproof 검증으로 이어가세요. 모든 경로에 사전 준비, 복사 가능한 명령, 예상 출력과 실패 대응 방법이 포함되어 있습니다.",
    meta: "TrustDB 온보딩 경로 · v1.0.0",
    primary: "10분 튜토리얼 시작",
    secondary: "먼저 증거 모델 이해하기",
    chooseEyebrow: "목표 선택",
    chooseTitle: ["읽는 순서를 고민하지 마세요.", "목표에서 시작하세요."],
    chooseLead: "여섯 경로는 동일한 증명 의미 체계를 공유합니다. 로컬에서 평가하고 애플리케이션에 연동한 뒤 안전하게 운영하세요.",
    paths: [
      ["10 MIN", "로컬에서 실행", "빈 디렉터리에서 L3 ProofBundle을 만들고 원본 파일이 바뀌지 않았는지 검증합니다.", "/docs/quick-start", "example.tdproof 생성"],
      ["BUILD", "Go SDK 연동", "로컬 서버를 시작하고 파일을 제출해 L4를 기다린 뒤 .sproof를 내보내 로컬에서 검증합니다.", "/docs/sdk", "실행 가능한 예제와 record.sproof 생성"],
      ["STREAM", "NATS ingress 추가", "JetStream으로 signed claim을 내구성 있게 모으고 timeout 또는 재시작 뒤 immutable L2 result를 복구합니다.", "/docs/nats-ingress", "제한된 broker 경로와 복구 규칙 확보"],
      ["VERIFY", "전달받은 증거 검증", "서비스와 네트워크를 사용할 수 없는 상태에서 독립적으로 확보한 신뢰 키로 증명을 다시 계산합니다.", "/docs/offline-verification", "오프라인 검증 결과 생성"],
      ["OPERATE", "프로덕션에 배포", "영구 데이터, 키 경계, 네트워크 보호, 상태 확인, 백업과 복구 리허설을 계획합니다.", "/docs/server", "운영 전 점검표 완성"],
      ["RECOVER", "일반적인 장애 해결", "권한, 키, 증명 준비 상태, 앵커링, Pebble 잠금, schema 오류를 증상별로 진단합니다.", "/docs/troubleshooting", "안전한 복구 절차 확보"],
    ],
    modelEyebrow: "학습 경로",
    modelTitle: ["이해하고 실행한 뒤", "프로덕션으로 확장하세요."],
    modelSteps: [
      ["01", "이해", "TrustDB가 무엇을 증명하고 무엇을 증명하지 않는지, L1–L5가 독립 검증 가능한 자료를 어떻게 더하는지 배웁니다."],
      ["02", "체험", "CLI로 키, claim, L3 증명을 만든 뒤 정상 성공과 변조 실패를 각각 확인합니다."],
      ["03", "연동", "Go SDK로 서명과 증명을 처리하고, 내구성 있는 집계가 필요하면 선택적 NATS / JetStream 쓰기 경로를 추가합니다."],
      ["04", "운영", "버전과 설정을 고정하고 신뢰 루트를 분리하며 네트워크 경계를 보호한 뒤 복구를 연습합니다."],
    ],
    boundaryTitle: "원본 파일은 TrustDB 밖에 둘 수 있으며, 검증할 때 TrustDB가 온라인일 필요도 없습니다.",
    boundaryBody: "핵심 서비스는 서명된 다이제스트와 선택한 메타데이터를 받은 뒤 영수증과 증명을 생성합니다. 검증자는 신뢰할 수 있는 별도 경로로 클라이언트와 서버 공개 키를 확보해야 하며, 증거 파일 안의 정보가 그 자체로 신뢰 루트가 되지는 않습니다.",
  },
  quickStart: {
    title: "10분 빠른 시작",
    lead: "빈 디렉터리에서 로컬 서명, L3 Merkle commit, 독립 검증과 변조 실패 테스트까지 완료합니다. 서버나 Go 도구 체인이 필요하지 않습니다.",
    duration: "10분",
    outcome: "example.tdproof와 다시 계산한 유효한 L3 결과",
    prerequisites: ["macOS 또는 Linux 터미널(Windows에서는 해당 ZIP과 PowerShell 사용)", "curl, tar, grep, shasum/sha256sum", "새 연습용 디렉터리. 프로덕션 키 디렉터리를 재사용하지 마세요"],
    downloadTitle: "1. 아카이브를 다운로드하고 먼저 검증하기",
    downloadBody: "릴리스 아카이브와 체크섬 목록을 다운로드합니다. 압축을 풀기 전에 반드시 검증하세요. 아래 예시는 Apple Silicon Mac 기준입니다.",
    downloadExpected: "체크섬 명령이 아카이브 이름 뒤에 OK를 출력합니다. 값이 다르면 즉시 중단하고 GitHub Releases에서 다시 다운로드하세요.",
    allPlatforms: "다른 플랫폼 선택",
    platformNoteTitle: "Linux와 Windows",
    platformNoteBody: "Linux에서는 sha256sum -c를 사용합니다. Windows에서는 해당 ZIP과 SHA256SUMS를 다운로드하고 Get-FileHash -Algorithm SHA256 결과를 비교한 뒤 압축을 풀어, 나머지 명령에서 PowerShell의 .\\bin\\trustdb.exe를 사용하세요.",
    linuxPathLabel: "Linux amd64: 다운로드, 검증 및 압축 풀기",
    windowsPathLabel: "Windows x86-64: 전체 PowerShell 안내",
    extractTitle: "2. 압축을 풀고 연습 파일 만들기",
    extractBody: "릴리스 디렉터리로 이동해 입력 파일을 명시적으로 만듭니다. 일회성 상태는 모두 .trustdb-dev 아래에 둡니다.",
    extractExpected: "version이 1.0.0을 출력하고 example.txt 내용이 hello TrustDB입니다.",
    keysTitle: "3. 일회용 클라이언트와 서버 키 생성하기",
    keysBody: "클라이언트 비밀 키는 콘텐츠 다이제스트에 서명하고 서버 비밀 키는 영수증에 서명합니다. 공개 키는 검증에 사용합니다.",
    keysWarning: "key generate은 같은 이름의 키 파일을 교체합니다. 새 연습 디렉터리에서 한 번만 실행하고, 이미 증거를 발급한 ID에는 다시 실행하지 마세요.",
    keysExpected: ".trustdb-dev에 client.key, client.pub, server.key, server.pub가 있습니다. 비밀 키를 검증자에게 보내지 마세요.",
    claimTitle: "4. 로컬에서 서명된 claim 만들기",
    claimBody: "CLI가 example.txt를 스트리밍하며 해시한 뒤 .tdclaim을 만듭니다. 원본 파일은 업로드되지 않습니다.",
    claimExpected: ".trustdb-dev/example.tdclaim이 존재하고 example.txt는 로컬에 그대로 있습니다.",
    commitTitle: "5. 로컬 Merkle 배치에 commit하기",
    commitBody: "로컬 commit은 별도의 연습용 WAL을 사용해 L3 ProofBundle을 만듭니다. 실행 중인 TrustDB 서버에는 제출하지 않습니다.",
    commitExpected: ".trustdb-dev/example.tdproof가 존재하고 proof inspect에 record_id, batch_id, tree_size가 표시됩니다.",
    verifyTitle: "6. 독립적으로 검증하기",
    verifyBody: "검증기는 선언된 증명 등급을 신뢰하지 않고 파일 다이제스트, 클라이언트 서명, 서버 영수증과 Merkle 경로를 다시 계산합니다.",
    verifyExpected: "명령이 종료 코드 0으로 끝나고 JSON에 \"valid\":true와 \"proof_level\":\"L3\"가 포함됩니다.",
    tamperTitle: "7. 변조 시 실패하는지 확인하기",
    tamperBody: "원본 파일을 복사해 한 줄을 추가한 뒤 같은 증명으로 검증합니다. 이 명령은 0이 아닌 상태로 종료되어야 합니다.",
    tamperExpected: "검증이 실패합니다. 증명은 원본 example.txt에만 해당하며 tampered.txt를 삭제해도 원래 증거에는 영향이 없습니다.",
    nextTitle: "다음 단계: 같은 증거 체인을 서비스에 연결하기",
    nextBody: "이 페이지는 로컬 L3에서 끝납니다. 공유 수집, 비동기 배치, L4 Global Log와 선택적 L5 외부 앵커링은 Go SDK 튜토리얼에서 계속하세요.",
  },
  sdk: {
    title: "Go SDK: 제출, 대기, 내보내기, 검증",
    lead: "상태를 확인하고 파일을 제출한 뒤 L4를 기다려 .sproof를 쓰고, 원본 파일과 로컬 신뢰 키만으로 검증하는 완전한 컴파일 가능 예제를 실행합니다.",
    duration: "20~30분",
    outcome: "record_id 하나, L4 이상인 record.sproof 하나, 로컬 검증 결과",
    prerequisites: ["10분 빠른 시작을 완료하고 example.txt와 .trustdb-dev 키를 보관해 둔 상태", "Go 1.26.5 또는 호환 버전", "터미널 두 개. 서비스는 127.0.0.1에만 바인딩"],
    serverTitle: "1. 상대 경로를 사용하는 로컬 서버 시작하기",
    serverBody: "이 명령은 production.yaml을 읽지 않으며 쓰기 가능한 모든 상태를 연습 디렉터리에 둡니다. Global Log가 활성화되어 레코드는 L2에서 L3, 이어서 L4로 비동기 승격됩니다.",
    serverExpected: "healthz가 정상 상태를 반환합니다. 이 터미널을 계속 실행해 두세요.",
    projectTitle: "2. 격리된 SDK 예제 디렉터리 만들기",
    projectBody: ".trustdb-dev 아래에 별도의 Go module을 만듭니다. 예제는 빠른 시작에서 남겨 둔 파일과 키를 상대 경로로 읽습니다. 변동 의존성 대신 v1.0.0을 고정하세요.",
    projectExpected: "go.mod가 github.com/wowtrust/trustdb v1.0.0을 고정하고, example.txt와 필요한 키 세 개는 원래 연습 위치에 그대로 남습니다.",
    codeTitle: "3. 컴파일 검사를 거친 완전한 예제 실행하기",
    codeBody: "아래의 전체 소스 코드를 펼쳐 복사한 뒤 현재 디렉터리에 main.go로 저장하세요. 저장소의 examples/sdk-onboarding/main.go가 이 페이지 코드의 유일한 기준 소스이며 Go 테스트에서 컴파일됩니다. 시간 제한을 둔 폴링을 사용하고 최초 L2 응답을 L4로 보고하지 않습니다.",
    codeExpected: "출력에는 일반적으로 먼저 submitted record_id=… proof_level=L2가 표시되고, 이어서 verified record_id=… proof_level=L4가 표시됩니다. record.sproof가 생성됩니다.",
    sourceLabel: "컴파일 검사를 거친 예제 소스 보기",
    asyncTitle: "예제가 기다리는 이유",
    asyncBody: "SubmitFile은 L2 수락 경계에서 반환합니다. 배치 마감과 Merkle 구체화가 L3를, Global Log 게시가 L4를 추가하며 정확히 일치하는 지원 sink의 성공한 anchor result가 L5를 추가합니다. 실제 외부 provider만 외부 시간 의미를 제공하며 noop/file은 그렇지 않습니다. 예제는 GlobalProof가 nil이 아닐 때까지 기다리고 시간 초과 시 명확히 실패합니다.",
    idempotencyTitle: "프로덕션 재시도에서 claim을 다시 만들지 마세요",
    idempotencyBody: "빠른 예제에서는 SDK가 임의의 멱등성 키를 생성합니다. 프로덕션에서 안전하게 재시도하려면 BuildSignedFileClaim을 한 번만 호출하고 네트워크 오류 후 같은 SignedClaim을 다시 제출하세요. 다시 만들면 produced_at/nonce가 달라지므로 같은 멱등성 키와 함께 사용할 수 없습니다.",
    offlineTitle: "4. 서비스를 중지한 뒤 다시 검증하기",
    offlineBody: "서버 터미널에서 Ctrl+C를 누른 뒤 CLI를 실행합니다. 이 과정은 TrustDB, 앵커 provider 또는 네트워크에 접근하지 않습니다.",
    offlineExpected: "서비스가 중지되어도 검증은 valid=true를 반환하며, 파일 안의 유효한 자료에서 증명 등급을 다시 계산합니다.",
  },
  offline: {
    title: ".sproof 완전 오프라인 검증",
    lead: "증거 수신자 입장에서 전달물을 확인하고 신뢰 루트를 독립적으로 확보한 뒤 TrustDB와 네트워크를 사용할 수 없는 상태에서 증명을 다시 계산합니다.",
    duration: "5~10분",
    outcome: "독립적으로 다시 계산한 L3, L4 또는 L5 결과와 기록된 변조 실패 한 건",
    prerequisites: ["example.txt와 같은 원본 파일", "record.sproof와 같은 해당 단일 파일 증거", "신뢰할 수 있는 별도 경로로 확보한 클라이언트와 서버 공개 키", "로컬 TrustDB CLI. 검증 중에는 네트워크를 끊고 서비스를 중지할 수 있습니다"],
    packageTitle: "1. 전달 패키지 확인하기",
    packageBody: ".sproof에는 ProofBundle이 내장되고 정확히 대응하는 GlobalLogProof와 AnchorResult가 포함될 수 있습니다. 빠진 자료를 보충하려고 서버를 조회하지 않습니다.",
    trustTitle: "증거는 스스로 신뢰 루트를 지정할 수 없습니다",
    trustBody: ".sproof 안이나 옆에 키가 있다는 이유만으로 신뢰하지 마세요. 계약 부속 문서, 통제된 설정, 오프라인 지문 확인 또는 다른 독립 경로로 클라이언트와 서버 공개 키를 고정하세요.",
    verifyTitle: "2. 네트워크를 끊고 검증하기",
    verifyBody: "검증기는 원본을 다시 읽고 모든 계층을 확인합니다. 출력 등급은 실제로 통과한 검증 단계에서 결정됩니다.",
    verifyExpected: "valid=true. ProofBundle만 있으면 최대 L3이고 유효한 GlobalLogProof는 L4를 제공합니다. L5에는 TreeSize와 RootHash가 정확히 일치해야 합니다. 양쪽 모두 NodeID/LogID를 제공하면 이 값들도 일치해야 하며, 지원되는 sink와 결정론적 anchor_id를 검사하고 OTS proof는 구조와 digest도 검증합니다.",
    levelTitle: "3. 등급을 정확히 해석하기",
    levels: [
      ["L3", "원본, 서명, 서버 영수증과 배치 Merkle 경로가 유효합니다.", "아직 Global Log 포함을 증명하지는 않습니다."],
      ["L4", "배치가 파일에 포함된 Signed Tree Head가 포괄하는 Global Log에 포함됩니다.", "외부 시간 앵커를 뜻하지는 않습니다."],
      ["L5", "TreeSize와 RootHash가 STH와 정확히 일치하고, 비어 있지 않은 ID 필드, sink envelope와 anchor_id가 검증되며 OTS proof에는 추가 검사가 적용됩니다.", "noop/file도 L5를 생성할 수 있지만 독립적인 외부 시간은 아닙니다."],
    ],
    skipTitle: "L4까지만 평가하기",
    skipBody: "--skip-anchor는 사용 가능한 L5 자료를 무시하고 Global Proof가 유효하면 L4를 보고합니다. L2/L3 서버 레코드를 L4로 승격하지는 않습니다.",
    tamperTitle: "4. 변조 실패 테스트 실행하기",
    tamperBody: "원본, Merkle path, STH signature, root, anchor_id 또는 검증되는 OTS 필드(TreeSize, 해시 알고리즘과 digest, 수락 시각)를 변경하면 검증에 실패해야 합니다. file/noop의 Proof 필드와 제출 시각, 캘린더 URL, 상태 코드 같은 OTS 진단 메타데이터는 보안 의미를 갖지 않으므로, 이런 필드만 바꾸는 방식으로 변조 테스트를 하지 마세요. 원본 파일 변경부터 시작하세요.",
    tamperExpected: "명령이 0이 아닌 코드로 종료됩니다. 원본 파일과 record.sproof를 복원하면 검증이 다시 성공해야 합니다.",
  },
  server: {
    title: "프로덕션 배포와 복구",
    lead: "안전한 로컬 노드에서 시작해 바이너리/Docker 경로, 영구 스토리지, 키 경계, 네트워크 보호, 상태 확인, 백업과 복구를 명확히 구성합니다.",
    duration: "30~60분과 복구 리허설 1회",
    outcome: "경계가 명확하고 모니터링, 백업, 복구가 가능한 단일 노드 TrustDB 배포",
    prerequisites: ["10분 빠른 시작을 완료하고 연습용 .trustdb-dev/server.key와 client.pub를 보관한 상태", "고정된 TrustDB 릴리스와 검증한 SHA-256", "바이너리 또는 Docker 배포 방식 결정", "영구 데이터, 로그, 키, key registry와 백업 위치 계획", "reverse proxy, mTLS 또는 네트워크 정책 계획. 보호되지 않은 쓰기 endpoint를 공개 인터넷에 노출하지 마세요"],
    localTitle: "1. 상대 경로로 스모크 테스트부터 시작하기",
    localBody: "이 명령은 릴리스 아카이브에서 비 root 사용자로 실행할 수 있습니다. WAL, Pebble, 증명 데이터 위치를 명시해 /var/lib 또는 /var/log에 실수로 쓰지 않습니다.",
    localExpected: "healthz가 성공하고 records가 페이지를 반환하며 metrics가 Prometheus 텍스트를 반환합니다.",
    dockerTitle: "2. 빠른 Docker 배포",
    dockerBody: "named volume은 상태와 첫 실행 때 생성된 키를 보존합니다. 이를 생략하면 컨테이너 삭제 시 ID와 증거 상태도 함께 삭제됩니다.",
    dockerExpected: "컨테이너가 healthy/running 상태이고 로그에 최초 키 생성이 표시되며 healthz가 성공합니다.",
    dockerBoundary: "Docker는 빠른 체험을 위해 데모 클라이언트 비밀 키를 서버 상태와 같은 볼륨에 저장합니다. 프로덕션에서는 클라이언트 비밀 키를 업무 애플리케이션에 보관하고 서버에는 해당 공개 키 또는 신뢰할 수 있는 registry만 설정하세요.",
    templateTitle: "3. 이후 production.yaml로 전환하기",
    templateBody: "릴리스 아카이브 경로는 config/production.yaml이고 소스 트리 경로는 configs/production.yaml입니다. 기본값은 /etc/trustdb, /var/lib/trustdb, /var/log/trustdb를 사용합니다. 먼저 디렉터리를 만들고 최소 권한을 설정한 뒤 키 경로를 교체하세요. run_profile은 관찰용 label일 뿐이며 --data-dir도 WAL, proofstore, 로그와 키를 자동으로 옮기지 않습니다.",
    templatesLabel: "설정 템플릿 보기",
    profilesTitle: "스토리지와 내구성 선택",
    profiles: [
      ["file", "가벼운 개발용 배치이며 고처리량 프로덕션 기준은 아닙니다."],
      ["Pebble", "권장하는 단일 노드 프로덕션 proofstore이며 실행 중인 서비스가 디렉터리 잠금을 소유합니다."],
      ["TiKV", "컴퓨트 노드는 TiKV 클러스터를 공유할 수 있지만, 하나의 proofstore namespace는 하나의 논리적 (node_id, log_id) 스트림에 속합니다. 같은 namespace의 active-active writer는 지원하지 않습니다."],
      ["fsync", "유효한 모드는 strict, group, batch이며 프로덕션 기본값으로 group을 권장합니다. benchmark-extreme.yaml은 benchmark profile이지 fsync 모드가 아닙니다."],
    ],
    anchorTitle: "앵커링 경계",
    anchorBody: "Docker 기본값인 noop sink는 스케줄링과 증거 흐름을 시험하지만 독립적인 외부 시간을 제공하지 않습니다. L5 외부 시간 의미가 필요하면 지원 provider를 설정하고 증거의 Signed Tree Head와 정확히 일치하는 immutable result만 인정하세요.",
    securityTitle: "네트워크와 접근 제어",
    securityBody: "TrustDB 업무 HTTP/gRPC endpoint는 일반 TLS, ID 인증 또는 tenant 권한 부여를 대신하지 않습니다. 통제된 네트워크에서 실행하고 reverse proxy, mTLS, API gateway, 방화벽 또는 네트워크 정책으로 ingress를 보호하세요. Admin Web은 기본적으로 꺼져 있으며, 활성화할 때는 자격 증명, session secret과 보안 HTTPS cookie를 별도로 설정해야 합니다.",
    backupTitle: "4. 서비스를 중지한 뒤 논리 백업을 만들고 검증하기",
    backupBody: "Pebble 디렉터리는 서비스와 백업 프로세스가 동시에 열 수 없습니다. 쓰기 서비스를 정상 종료한 뒤 백업을 생성하고 검증해 새 경로에 복구하세요. 첫 복구 리허설에서 원본 디렉터리를 덮어쓰지 마세요.",
    backupBoundary: ".tdbackup에는 bundle, root, Global Log, STH, anchor result와 scheduler state를 포함한 proofstore 증거 상태만 들어갑니다. WAL, WAL checkpoint, 설정, 비밀 키, 원본 파일, key registry와 registry 신뢰 자료는 포함되지 않습니다. 이 자료들은 같은 복구 시점을 기준으로 별도 백업하고, 복구한 proofstore에는 일치하는 WAL과 registry만 연결해야 하며 임의의 오래된 상태를 섞지 마세요.",
    checklistTitle: "운영 전 점검표",
    checklist: ["이미지 digest 또는 릴리스 버전을 고정하고 SHA-256 보관", "클라이언트와 서버 비밀 키를 분리하고 통제된 경로로 공개 키 배포", "모든 영구 및 로그 경로의 용량과 권한 모니터링", "보호된 네트워크 또는 TLS/mTLS ingress 뒤에서만 쓰기 endpoint 공개", "실제 anchor sink 의미 확인. noop를 외부 시간으로 취급하지 않기", "healthz, records, metrics와 정상 종료 검증", "서비스를 중지한 뒤 backup, backup verify와 독립 경로 복구 리허설 완료", "업그레이드 전에 release notes를 읽고 복사본에서 schema와 증거 검증"],
    apiTitle: "읽기 및 연동 endpoint",
    apiBody: "HTTP 쓰기는 손으로 작성한 JSON이 아니라 결정론적 CBOR을 사용하며, gRPC는 프로젝트의 결정론적 CBOR codec을 사용합니다. 업무 쓰기에는 Go SDK 또는 데스크톱 클라이언트를 권장합니다. curl은 상태 확인과 읽기 전용 진단에 적합합니다.",
  },
  troubleshooting: {
    title: "문제 해결",
    lead: "증상에서 시작해 가장 짧은 진단 경로를 따르세요. 모든 해결책은 상태를 삭제해 오류를 숨기지 않고 키, WAL, proofstore와 증거를 보존합니다.",
    duration: "항목당 2~10분",
    outcome: "확인된 원인, 실행 가능한 진단과 증명 경계를 보존하는 다음 단계",
    introTitle: "먼저 현장을 보존하세요",
    introBody: "버전, 전체 오류, 시작 인자와 관련 경로 권한을 기록하세요. key generate을 다시 실행하거나 Pebble/WAL을 삭제하거나 백업을 덮어쓰거나 공개 issue에 비밀 키를 붙여 넣지 마세요.",
    diagnosticsTitle: "일반 진단",
    causeLabel: "가능한 원인",
    actionLabel: "안전한 다음 단계",
    cards: [
      ["permission denied / cannot create log", "production.yaml이 권한 없이 /var/lib, /var/log 또는 /etc 경로를 가리킵니다.", "로컬에서는 튜토리얼의 명시적인 상대 경로를 사용하세요. 프로덕션에서는 전용 사용자와 디렉터리를 만든 뒤 owner/mode를 명시적으로 설정하세요. 상태 일부를 sudo로 만든 뒤 다른 사용자로 계속하지 마세요."],
      ["signature verification failed / key mismatch", "원본이 바뀌었거나 검증자가 잘못된 클라이언트/서버 키를 사용했거나 key generate이 이미 증거를 발급한 ID를 교체했습니다.", "원본 다이제스트와 신뢰할 수 있는 경로로 보관한 지문을 비교하세요. 현재 파일을 보존하세요. 새 키를 생성해도 과거 증거를 복구할 수 없습니다."],
      ["proof not found / still L2", "claim은 수락되었지만 배치 마감이나 증명 구체화가 아직 끝나지 않았습니다.", "제한된 backoff로 GetProofBundle/ExportSingleProof를 재시도하세요. L2는 실패가 아니며 시간 제한 없이 무한 폴링하지 마세요."],
      ["server verification requires L4", "trustdb verify --server는 Global Log 증명을 가져오므로 L2/L3 레코드는 아직 조건을 만족할 수 없습니다.", "L4가 될 때까지 기다리거나 이미 내보낸 L3 ProofBundle을 검증하세요. --skip-anchor는 L5만 무시하며 L3를 L4로 올리지 않습니다."],
      ["L5 never appears", "앵커링이 꺼져 있거나 고정 창이 아직 만료되지 않았거나 provider 게시가 실패해 재시도 중입니다.", "앵커 설정, sink, max_delay, scheduler와 provider 로그를 확인하세요. 성공한 noop/file 결과도 L5를 생성하지만 독립적인 외부 시간은 제공하지 않습니다. OTS calendar의 최초 수락으로 L5가 생성되며 이후 업그레이드는 proof를 보강할 뿐입니다. proof_level을 수동으로 편집하지 마세요."],
      ["resource temporarily unavailable / LOCK", "실행 중인 서비스가 Pebble 디렉터리를 소유하므로 다른 backup 또는 server 프로세스가 열 수 없습니다.", "서비스를 정상 종료하고 프로세스가 끝났는지 확인한 뒤 backup create를 실행하세요. 새 대상 디렉터리에 복구하세요."],
      ["schema/version mismatch", "바이너리가 다른 schema/format 버전의 store 또는 backup을 거부합니다.", "원본을 보존하고 이를 생성한 TrustDB 버전을 확인하세요. 지원되는 마이그레이션을 따르거나 먼저 일치하는 버전으로 내보내세요. 버전 marker를 삭제하거나 이중 읽기 호환 코드를 추가하지 마세요."],
    ],
    askTitle: "아직 해결되지 않았나요?",
    askBody: "GitHub issue에 TrustDB 버전, 운영체제, 재현 절차, 민감 정보를 제거한 설정 필드, 전체 오류와 이미 실행한 진단 명령을 제공하세요. 실제 비밀 키, token, 프로덕션 주소, 고객 데이터 또는 민감 정보를 제거하지 않은 증거를 업로드하지 마세요.",
    openIssueLabel: "issue 등록하기",
  },
};
