const content = {
  "zh-CN": {
    lang: "zh-CN",
    updated: "更新于 2026.07.24",
    version: "适用于包含 NATSIngressClient 的当前 main 或后续版本",
    title: "可选 NATS / JetStream 存证入口",
    lead: "在 TrustDB 前增加耐久缓冲、多生产者汇聚与有界流量分发，同时保持原有签名、WAL、证明和离线验证语义。",
    duration: "20–30 分钟",
    outcome: "一个默认关闭、可恢复结果、权限边界清晰的 JetStream 写入通道",
    prerequisites: ["已能运行 TrustDB main 或包含 NATSIngressClient 的后续版本", "可用的 NATS JetStream broker", "已有可被 TrustDB 信任的客户端签名身份", "可以配置 broker account、TLS 与 subject 权限"],
    boundaryTitle: "NATS 只替换写入传输，不替换 TrustDB 的证据数据库。",
    boundaryBody: "NATSIngressClient 负责发布 signed claim 和恢复 acceptance result；record 查询、proof 导出、Global Log evidence 与 anchor 读取仍使用 HTTP/gRPC sdk.Client。",
    ackTitle: "先分清两个确认",
    ackBody: "JetStream 与 TrustDB 各自拥有一个耐久边界。只有第二个边界才代表 L2。",
    ackSteps: [
      ["01", "JetStream publish ACK", "请求已进入 ingress stream，但 TrustDB 可能尚未校验或写入 WAL。"],
      ["02", "TrustDB accepted result", "签名和密钥状态校验通过，记录跨过正常 WAL acceptance 边界并报告 L2。"],
      ["03", "Result before ACK", "服务端先保存不可变 result，再确认原 ingress delivery；超时或重启后仍可恢复。"],
    ],
    localTitle: "1. 启动本地 JetStream 并开启入口",
    localBody: "下面的 broker 只用于本地演练。保留已有可运行的 server、key、WAL 与 proofstore 设置，再修改生成配置中的 nats 段。",
    localExpected: "启动日志出现 optional NATS ingress started，并显示 ingress/result/DLQ stream、durable consumer 和最终 worker 数量。",
    localNoteTitle: "默认关闭",
    localNoteBody: "nats.enabled=false 时，TrustDB 不连接 broker、不检查或创建资源，也不改变 HTTP/gRPC。开启后 broker 不可达或拓扑不兼容都会让启动失败关闭。",
    topologyTitle: "2. 让四个资源各司其职",
    topologyBody: "provision=true 只创建缺失资源；已有资源必须精确匹配，TrustDB 不会静默修改。provision=false 适合由基础设施流程预建拓扑。",
    topologyRows: [
      ["Ingress stream", "WorkQueue 保存 trustdb.ingress.v1.claims；DiscardNew 和容量限制构成 broker 背压。"],
      ["Durable consumer", "显式 ACK、精确 subject filter、MaxAckPending 和 MaxDeliver 限制并发与重投。"],
      ["Result stream", "每个 request subject 只保存一条不可变 accepted 或 terminal error result。"],
      ["Dead-letter stream", "非法 subject/header/schema/message ID/CBOR 在终止原 delivery 前完整留存。"],
    ],
    flowTitle: "3. 背压、重试和关闭",
    flowBody: "Worker 不增加第二个进程内队列。JetStream 限制 broker 分发，共用 submission service 继续使用与 HTTP/gRPC 相同的阻塞式队列背压。",
    flowRows: [
      ["容量达到上限", "Ingress publish 失败；生产者应有界重试。Result/DLQ 满时服务端不 ACK 原 delivery，并持续重试 outcome write。"],
      ["暂时性失败", "合法请求按 nak_delay 重投；达到 max_deliver 后写入不可变终态错误。"],
      ["重复请求", "完全相同的 SignedClaim 产生相同 request ID，可恢复同一个不可变结果。"],
      ["优雅关闭", "未完成 delivery 保持未确认，重启后由同一 durable consumer 继续处理。"],
    ],
    sdkTitle: "4. 用 Go SDK 发布并恢复结果",
    sdkBody: "同步接口适合一次调用等待完成；分步接口允许应用先持久化 NATSSubmission，再在断连或重启后恢复结果。",
    sdkExpected: "accepted result 包含 record_id、L2 proof_level、server record 与 accepted receipt；终态拒绝返回可用 errors.As 检查的 *sdk.Error。",
    resumeTitle: "恢复 handle 的规则",
    resumeBody: "必须一起保存 MessageID 与原始 SignedClaim，并防止被修改。WaitResult 会重新绑定两者，先订阅精确结果 subject，再读取耐久 snapshot；不能只信任外部传入的 message ID。",
    securityTitle: "5. 分离 broker 身份与权限",
    securityBody: "Server 与 producer 使用不同账号。凭据不得写进 URL；credentials file、username/password 与 token 三种认证方式互斥。TLS 应校验 CA 与 server name。",
    securityChecklist: ["Server：检查拓扑、消费/ACK durable consumer、发布 result 与 DLQ；只有 provision=true 才需要创建资源", "Producer：检查 ingress/result stream、只发布具体 ingress subject、订阅自己请求的精确 result subject并读取最后一条结果", "Producer 不需要 stream 更新/删除、consumer 管理或 DLQ 权限", "放量前同时验证一次实时 publish-and-wait 和一次已存结果恢复"],
    recoveryTitle: "6. 明确保留与恢复边界",
    recoveryBody: "result_max_age/result_max_bytes 决定调用方能恢复多久；默认 result age 为 24h。stream_storage=memory 是有意易失，file 与 replicas 决定 broker 侧耐久性。",
    recoveryChecklist: ["观察 ingress backlog、consumer pending/redelivery/unacked 与 result/DLQ 容量", "重复 worker delivery error 时检查 submission、broker 与 outcome store", "已有拓扑不兼容时按报错逐项修正，不让 TrustDB自动改写", "结果过期后 WaitResult 无法补回；按业务恢复窗口设置 retention"],
    backupTitle: "Broker 状态不在 .tdbackup 中",
    backupBody: "Ingress message、NATS result 与 dead letter 是传输状态，不是 .sproof，也不包含在 TrustDB 逻辑备份里。Broker 数据必须按 JetStream storage 与 replication 策略单独保全。",
    fullGuideLabel: "查看仓库中的完整字段与运维指南",
    nextLabel: "继续查看服务部署",
    sdkLinkLabel: "需要 broker 缓冲与分流？查看 NATS ingress 教程",
    serverLinkLabel: "为服务增加可选 JetStream 入口",
  },
  en: {
    lang: "en",
    updated: "Updated 2026-07-24",
    version: "For current main or a later release containing NATSIngressClient",
    title: "Optional NATS / JetStream ingress",
    lead: "Put durable buffering, multi-producer fan-in, and bounded flow distribution in front of TrustDB without changing signatures, WAL, proofs, or offline verification.",
    duration: "20–30 minutes",
    outcome: "A default-off JetStream write path with recoverable results and explicit permission boundaries",
    prerequisites: ["TrustDB main or a later release containing NATSIngressClient", "A reachable NATS JetStream broker", "An existing client signing identity trusted by TrustDB", "Access to configure broker accounts, TLS, and subject permissions"],
    boundaryTitle: "NATS replaces only the write transport, not the TrustDB evidence database.",
    boundaryBody: "NATSIngressClient publishes signed claims and recovers acceptance results. Continue to use the HTTP/gRPC sdk.Client for records, proof export, Global Log evidence, and anchor reads.",
    ackTitle: "Separate the two acknowledgements",
    ackBody: "JetStream and TrustDB each own a durable boundary. Only the second boundary means L2.",
    ackSteps: [
      ["01", "JetStream publish ACK", "The request is stored in the ingress stream, but TrustDB may not have validated it or written WAL yet."],
      ["02", "TrustDB accepted result", "Signature and key-state checks passed, and the record crossed the normal WAL acceptance boundary at L2."],
      ["03", "Result before ACK", "The server stores the immutable result before acknowledging the ingress delivery, so callers can recover after timeout or restart."],
    ],
    localTitle: "1. Start local JetStream and enable ingress",
    localBody: "The broker below is for local evaluation only. Keep an existing runnable server, key, WAL, and proofstore configuration, then change its generated nats section.",
    localExpected: "Startup logs include optional NATS ingress started and show the ingress/result/DLQ streams, durable consumer, and resolved worker count.",
    localNoteTitle: "Default off",
    localNoteBody: "With nats.enabled=false, TrustDB does not connect, inspect or create resources, or change HTTP/gRPC. Once enabled, an unavailable broker or incompatible topology fails startup closed.",
    topologyTitle: "2. Give each resource one job",
    topologyBody: "provision=true creates only missing resources. Existing resources must match exactly and are never silently rewritten. Use provision=false when infrastructure owns topology.",
    topologyRows: [
      ["Ingress stream", "WorkQueue storage for trustdb.ingress.v1.claims; DiscardNew and capacity limits provide broker backpressure."],
      ["Durable consumer", "Explicit ACK, exact subject filter, MaxAckPending, and MaxDeliver bound concurrency and redelivery."],
      ["Result stream", "One immutable accepted or terminal-error result per request subject."],
      ["Dead-letter stream", "Preserves malformed subject/header/schema/message-ID/CBOR deliveries before terminating the original delivery."],
    ],
    flowTitle: "3. Backpressure, retry, and shutdown",
    flowBody: "The worker adds no second in-process queue. JetStream bounds broker delivery while the shared submission service keeps the same blocking queue backpressure as HTTP/gRPC.",
    flowRows: [
      ["Capacity reached", "Ingress publish fails and producers apply bounded retry. A full result/DLQ stream prevents ACK and makes the server retry outcome storage."],
      ["Transient failure", "Valid requests redeliver after nak_delay; after max_deliver, TrustDB stores an immutable terminal error."],
      ["Duplicate request", "The exact same SignedClaim has the same request ID and recovers the same immutable result."],
      ["Graceful shutdown", "Unfinished deliveries remain unacknowledged and resume through the same durable consumer after restart."],
    ],
    sdkTitle: "4. Publish and recover with the Go SDK",
    sdkBody: "Use the synchronous method for one-call completion, or persist NATSSubmission between publish and wait to recover after disconnection or process restart.",
    sdkExpected: "An accepted result contains record_id, L2 proof_level, the server record, and accepted receipt. Terminal rejection returns *sdk.Error for errors.As.",
    resumeTitle: "Submission handle rule",
    resumeBody: "Persist MessageID and the original SignedClaim together and protect both from modification. WaitResult rebinds them, subscribes to the exact result subject, then reads the durable snapshot. Never trust an external message ID alone.",
    securityTitle: "5. Separate broker identities and permissions",
    securityBody: "Use different accounts for the server and producers. Never put credentials in URLs. Credentials-file, username/password, and token authentication are mutually exclusive; TLS should verify the CA and server name.",
    securityChecklist: ["Server: inspect topology, consume/ACK the durable consumer, publish result and DLQ; resource creation is needed only with provision=true", "Producer: inspect ingress/result streams, publish only the concrete ingress subject, subscribe to its exact result subjects, and read their last result", "Producer does not need stream update/delete, consumer management, or DLQ access", "Before traffic, test both live publish-and-wait and stored-result recovery"],
    recoveryTitle: "6. Define retention and recovery boundaries",
    recoveryBody: "result_max_age and result_max_bytes determine how long callers can recover. The default result age is 24h. stream_storage=memory is intentionally volatile; file storage and replicas define broker durability.",
    recoveryChecklist: ["Monitor ingress backlog, consumer pending/redelivery/unacked, and result/DLQ capacity", "Investigate repeated worker delivery errors across submission, broker, and outcome storage", "Fix incompatible topology field by field; TrustDB intentionally does not mutate it", "WaitResult cannot recover an expired result, so size retention for the application recovery window"],
    backupTitle: "Broker state is outside .tdbackup",
    backupBody: "Ingress messages, NATS results, and dead letters are transport state, not .sproof evidence and not part of TrustDB logical backups. Protect broker data separately through JetStream storage and replication policy.",
    fullGuideLabel: "Open the complete repository field and operations guide",
    nextLabel: "Continue to server deployment",
    sdkLinkLabel: "Need broker buffering and fan-out? Open the NATS ingress guide",
    serverLinkLabel: "Add an optional JetStream ingress to the service",
  },
  fr: {
    lang: "fr",
    updated: "Mis à jour le 24/07/2026",
    version: "Pour la branche main actuelle ou une version ultérieure contenant NATSIngressClient",
    title: "Entrée NATS / JetStream facultative",
    lead: "Ajoutez un tampon durable, l’agrégation de plusieurs producteurs et une distribution bornée devant TrustDB sans modifier les signatures, le WAL, les preuves ni la vérification hors ligne.",
    duration: "20 à 30 minutes",
    outcome: "Un chemin d’écriture JetStream désactivé par défaut, avec résultats récupérables et permissions explicites",
    prerequisites: ["TrustDB main ou une version ultérieure contenant NATSIngressClient", "Un broker NATS JetStream accessible", "Une identité de signature cliente déjà approuvée par TrustDB", "La possibilité de configurer les comptes, TLS et permissions de sujets"],
    boundaryTitle: "NATS remplace uniquement le transport d’écriture, pas la base de preuves TrustDB.",
    boundaryBody: "NATSIngressClient publie les claims signés et récupère les résultats d’acceptation. Utilisez toujours sdk.Client en HTTP/gRPC pour les enregistrements, l’export de preuves, le Global Log et les ancres.",
    ackTitle: "Distinguer les deux accusés",
    ackBody: "JetStream et TrustDB ont chacun une frontière durable. Seule la seconde correspond à L2.",
    ackSteps: [["01", "ACK de publication JetStream", "La requête est stockée dans le stream, mais TrustDB ne l’a peut-être pas encore validée ni écrite dans le WAL."], ["02", "Résultat accepté TrustDB", "La signature et l’état de la clé sont valides ; l’enregistrement a franchi la frontière WAL L2."], ["03", "Résultat avant ACK", "Le serveur stocke le résultat immuable avant d’acquitter la livraison ; il reste récupérable après délai ou redémarrage."]],
    localTitle: "1. Démarrer JetStream localement et activer l’entrée",
    localBody: "Le broker ci-dessous sert uniquement à l’évaluation locale. Conservez une configuration serveur, clés, WAL et proofstore déjà fonctionnelle, puis modifiez sa section nats générée.",
    localExpected: "Les logs contiennent optional NATS ingress started avec les streams ingress/result/DLQ, le consumer durable et le nombre de workers.",
    localNoteTitle: "Désactivé par défaut",
    localNoteBody: "Avec nats.enabled=false, TrustDB ne se connecte pas et ne modifie pas HTTP/gRPC. Une fois activé, un broker indisponible ou une topologie incompatible bloque le démarrage.",
    topologyTitle: "2. Un rôle par ressource",
    topologyBody: "provision=true crée seulement les ressources absentes. Les ressources existantes doivent correspondre exactement et ne sont jamais réécrites. Utilisez provision=false si l’infrastructure gère la topologie.",
    topologyRows: [["Stream ingress", "WorkQueue pour trustdb.ingress.v1.claims ; DiscardNew et les limites fournissent la contre-pression."], ["Consumer durable", "ACK explicite, filtre exact, MaxAckPending et MaxDeliver bornent concurrence et nouvelle livraison."], ["Stream de résultats", "Un résultat accepté ou une erreur terminale immuable par requête."], ["Dead-letter stream", "Conserve les livraisons malformées avant de terminer la livraison originale."]],
    flowTitle: "3. Contre-pression, reprise et arrêt",
    flowBody: "Le worker n’ajoute pas de seconde file en mémoire. JetStream borne la livraison et le service de soumission partagé conserve la même contre-pression bloquante que HTTP/gRPC.",
    flowRows: [["Capacité atteinte", "La publication ingress échoue et le producteur applique une reprise bornée. Un result/DLQ plein empêche l’ACK et force la reprise du stockage."], ["Échec temporaire", "Une requête valide est relivrée après nak_delay ; après max_deliver, une erreur terminale immuable est stockée."], ["Doublon", "Le même SignedClaim garde le même request ID et retrouve le même résultat."], ["Arrêt propre", "Les livraisons inachevées restent non acquittées et reprennent après redémarrage."]],
    sdkTitle: "4. Publier et récupérer avec le SDK Go",
    sdkBody: "Utilisez la méthode synchrone pour attendre en un appel, ou persistez NATSSubmission entre publish et wait pour reprendre après une déconnexion ou un redémarrage.",
    sdkExpected: "Un résultat accepté contient record_id, proof_level L2, server record et accepted receipt. Un rejet terminal renvoie *sdk.Error.",
    resumeTitle: "Règle du handle de soumission",
    resumeBody: "Persistez ensemble MessageID et le SignedClaim original. WaitResult les relie à nouveau, s’abonne au sujet exact puis lit le snapshot durable. Ne faites jamais confiance à un message ID seul.",
    securityTitle: "5. Séparer les identités et permissions",
    securityBody: "Utilisez des comptes distincts pour serveur et producteurs. Aucun secret dans les URL. Les trois modes d’authentification sont exclusifs et TLS doit vérifier CA et nom du serveur.",
    securityChecklist: ["Serveur : inspecter la topologie, consommer/ACK, publier result et DLQ ; créer seulement avec provision=true", "Producteur : inspecter ingress/result, publier le sujet concret, s’abonner aux résultats exacts et lire le dernier résultat", "Aucun besoin de modifier/supprimer les streams, gérer les consumers ou lire le DLQ", "Tester une attente en direct et la récupération d’un résultat déjà stocké"],
    recoveryTitle: "6. Fixer les limites de conservation et reprise",
    recoveryBody: "result_max_age et result_max_bytes déterminent la fenêtre de récupération ; l’âge par défaut est 24h. memory est volontairement volatile ; file et replicas définissent la durabilité broker.",
    recoveryChecklist: ["Surveiller backlog, pending/redelivery/unacked et capacité result/DLQ", "Analyser les erreurs répétées du worker sur soumission, broker et stockage", "Corriger chaque champ incompatible sans mutation automatique", "Dimensionner la rétention selon la fenêtre de reprise de l’application"],
    backupTitle: "L’état du broker est hors de .tdbackup",
    backupBody: "Messages ingress, résultats NATS et dead letters sont un état de transport, pas une preuve .sproof ni une sauvegarde logique TrustDB. Protégez-les séparément via le stockage et la réplication JetStream.",
    fullGuideLabel: "Voir le guide complet des champs et opérations",
    nextLabel: "Continuer vers le déploiement serveur",
    sdkLinkLabel: "Besoin d’un tampon broker ? Voir l’entrée NATS",
    serverLinkLabel: "Ajouter une entrée JetStream facultative",
  },
  ko: {
    lang: "ko",
    updated: "2026.07.24 업데이트",
    version: "NATSIngressClient가 포함된 현재 main 또는 이후 버전용",
    title: "선택적 NATS / JetStream 수집 경로",
    lead: "서명, WAL, 증명, 오프라인 검증 의미를 바꾸지 않고 TrustDB 앞에 내구성 버퍼, 다중 생산자 집계, 제한된 흐름 분배를 추가합니다.",
    duration: "20–30분",
    outcome: "기본 비활성, 결과 복구 가능, 권한 경계가 명확한 JetStream 쓰기 경로",
    prerequisites: ["NATSIngressClient가 포함된 TrustDB main 또는 이후 버전", "접근 가능한 NATS JetStream broker", "TrustDB가 신뢰하는 기존 클라이언트 서명 identity", "broker account, TLS, subject 권한 설정 권한"],
    boundaryTitle: "NATS는 쓰기 전송만 바꾸며 TrustDB 증거 데이터베이스를 대체하지 않습니다.",
    boundaryBody: "NATSIngressClient는 signed claim을 게시하고 acceptance result를 복구합니다. record, proof export, Global Log evidence, anchor 조회는 HTTP/gRPC sdk.Client를 계속 사용합니다.",
    ackTitle: "두 ACK를 구분하세요",
    ackBody: "JetStream과 TrustDB는 각각 내구성 경계를 가집니다. 두 번째 경계만 L2입니다.",
    ackSteps: [["01", "JetStream publish ACK", "요청이 ingress stream에 저장되었지만 TrustDB 검증이나 WAL 기록은 아직일 수 있습니다."], ["02", "TrustDB accepted result", "서명과 키 상태 검증을 통과하고 정상 WAL acceptance 경계인 L2를 넘었습니다."], ["03", "ACK 전에 result 저장", "서버는 immutable result를 먼저 저장하므로 timeout이나 재시작 뒤에도 복구할 수 있습니다."]],
    localTitle: "1. 로컬 JetStream을 시작하고 ingress 활성화",
    localBody: "아래 broker는 로컬 평가용입니다. 이미 동작하는 server, key, WAL, proofstore 설정을 유지하고 생성된 nats 섹션만 변경합니다.",
    localExpected: "로그에 optional NATS ingress started와 ingress/result/DLQ stream, durable consumer, worker 수가 표시됩니다.",
    localNoteTitle: "기본 비활성",
    localNoteBody: "nats.enabled=false이면 broker에 연결하거나 리소스를 검사/생성하지 않으며 HTTP/gRPC도 바뀌지 않습니다. 활성화 후 broker 불가 또는 topology 불일치는 시작 실패입니다.",
    topologyTitle: "2. 네 리소스의 역할 분리",
    topologyBody: "provision=true는 없는 리소스만 만듭니다. 기존 리소스는 정확히 일치해야 하며 자동 변경하지 않습니다. 인프라가 topology를 관리하면 false를 사용합니다.",
    topologyRows: [["Ingress stream", "trustdb.ingress.v1.claims WorkQueue. DiscardNew와 용량 제한이 broker backpressure를 만듭니다."], ["Durable consumer", "명시적 ACK, 정확한 filter, MaxAckPending, MaxDeliver로 동시성과 redelivery를 제한합니다."], ["Result stream", "요청 subject마다 accepted 또는 terminal error 결과 한 개만 immutable하게 저장합니다."], ["Dead-letter stream", "잘못된 subject/header/schema/message ID/CBOR를 원본 종료 전에 보존합니다."]],
    flowTitle: "3. Backpressure, retry, shutdown",
    flowBody: "worker는 두 번째 인메모리 큐를 만들지 않습니다. JetStream이 분배를 제한하고 공용 submission service는 HTTP/gRPC와 같은 blocking backpressure를 유지합니다.",
    flowRows: [["용량 도달", "Ingress publish가 실패하고 생산자는 제한된 retry를 적용합니다. Result/DLQ가 가득 차면 ACK하지 않고 저장을 재시도합니다."], ["일시적 실패", "유효 요청은 nak_delay 뒤 재전달되며 max_deliver 이후 immutable terminal error가 저장됩니다."], ["중복 요청", "완전히 같은 SignedClaim은 같은 request ID와 결과를 사용합니다."], ["정상 종료", "미완료 delivery는 미확인 상태로 남고 재시작 후 같은 consumer가 계속 처리합니다."]],
    sdkTitle: "4. Go SDK로 게시하고 결과 복구",
    sdkBody: "동기 메서드는 한 번에 기다리고, 분리 메서드는 publish와 wait 사이에 NATSSubmission을 저장해 연결 종료나 재시작 뒤 복구합니다.",
    sdkExpected: "accepted result에는 record_id, L2 proof_level, server record, accepted receipt가 있습니다. terminal rejection은 *sdk.Error입니다.",
    resumeTitle: "Submission handle 규칙",
    resumeBody: "MessageID와 원본 SignedClaim을 함께 저장하고 변경을 막으세요. WaitResult는 두 값을 다시 결합하고 정확한 결과 subject를 구독한 뒤 durable snapshot을 읽습니다.",
    securityTitle: "5. Broker identity와 권한 분리",
    securityBody: "server와 producer 계정을 분리하고 URL에 credential을 넣지 마세요. 인증 모드는 상호 배타적이며 TLS는 CA와 server name을 검증해야 합니다.",
    securityChecklist: ["Server: topology 조회, durable consumer consume/ACK, result/DLQ publish; provision=true일 때만 생성 권한", "Producer: ingress/result 조회, 구체 ingress subject만 publish, 정확한 result subject subscribe 및 마지막 결과 조회", "Producer는 stream 변경/삭제, consumer 관리, DLQ 접근 불필요", "트래픽 전 live publish-and-wait와 stored-result recovery 모두 테스트"],
    recoveryTitle: "6. Retention과 recovery 경계 설정",
    recoveryBody: "result_max_age/result_max_bytes가 복구 기간을 결정하며 기본 age는 24h입니다. memory는 의도적으로 휘발성이며 file과 replicas가 broker 내구성을 정합니다.",
    recoveryChecklist: ["ingress backlog, pending/redelivery/unacked, result/DLQ 용량 모니터링", "반복 worker 오류는 submission, broker, outcome storage를 함께 조사", "불일치 topology는 필드별 수정하고 자동 변경하지 않음", "애플리케이션 복구 창에 맞춰 retention 설정"],
    backupTitle: "Broker 상태는 .tdbackup 밖에 있습니다",
    backupBody: "Ingress message, NATS result, dead letter는 전송 상태이며 .sproof나 TrustDB 논리 백업이 아닙니다. JetStream storage와 replication 정책으로 별도 보호하세요.",
    fullGuideLabel: "전체 필드 및 운영 가이드 보기",
    nextLabel: "서버 배포로 계속",
    sdkLinkLabel: "Broker 버퍼가 필요하면 NATS ingress 가이드 보기",
    serverLinkLabel: "서비스에 선택적 JetStream ingress 추가",
  },
  ru: {
    lang: "ru",
    updated: "Обновлено 24.07.2026",
    version: "Для текущей main или более позднего выпуска с NATSIngressClient",
    title: "Необязательный вход NATS / JetStream",
    lead: "Добавьте перед TrustDB долговечный буфер, сбор от многих производителей и ограниченное распределение потока, не меняя подписи, WAL, доказательства и офлайн-проверку.",
    duration: "20–30 минут",
    outcome: "Отключённый по умолчанию канал записи JetStream с восстановлением результата и явными границами прав",
    prerequisites: ["TrustDB main или более поздний выпуск с NATSIngressClient", "Доступный broker NATS JetStream", "Клиентская подпись, которой уже доверяет TrustDB", "Возможность настроить accounts, TLS и права subjects"],
    boundaryTitle: "NATS заменяет только транспорт записи, а не базу доказательств TrustDB.",
    boundaryBody: "NATSIngressClient публикует signed claim и восстанавливает acceptance result. Для records, export proof, Global Log evidence и anchors используйте HTTP/gRPC sdk.Client.",
    ackTitle: "Разделяйте два подтверждения",
    ackBody: "У JetStream и TrustDB разные долговечные границы. Только вторая означает L2.",
    ackSteps: [["01", "JetStream publish ACK", "Запрос сохранён в ingress stream, но TrustDB мог ещё не проверить его и не записать WAL."], ["02", "TrustDB accepted result", "Проверки подписи и ключа пройдены, запись пересекла обычную WAL-границу L2."], ["03", "Result до ACK", "Сервер сохраняет неизменяемый result до подтверждения delivery, поэтому его можно восстановить после timeout или restart."]],
    localTitle: "1. Запустите локальный JetStream и включите вход",
    localBody: "Broker ниже предназначен только для локальной проверки. Сохраните рабочие настройки server, keys, WAL и proofstore, затем измените созданный раздел nats.",
    localExpected: "В логах есть optional NATS ingress started с ingress/result/DLQ streams, durable consumer и числом workers.",
    localNoteTitle: "По умолчанию выключено",
    localNoteBody: "При nats.enabled=false TrustDB не подключается, не создаёт ресурсы и не меняет HTTP/gRPC. После включения недоступный broker или несовместимая topology блокируют запуск.",
    topologyTitle: "2. Отдельная роль для каждого ресурса",
    topologyBody: "provision=true создаёт только отсутствующие ресурсы. Существующие должны точно совпадать и не переписываются. При внешнем управлении topology используйте false.",
    topologyRows: [["Ingress stream", "WorkQueue для trustdb.ingress.v1.claims; DiscardNew и лимиты создают broker backpressure."], ["Durable consumer", "Explicit ACK, точный filter, MaxAckPending и MaxDeliver ограничивают параллелизм и redelivery."], ["Result stream", "Один неизменяемый accepted или terminal-error result на request subject."], ["Dead-letter stream", "Сохраняет повреждённые deliveries до завершения исходного сообщения."]],
    flowTitle: "3. Backpressure, retry и shutdown",
    flowBody: "Worker не создаёт вторую очередь в памяти. JetStream ограничивает доставку, а общий submission service сохраняет блокирующий backpressure HTTP/gRPC.",
    flowRows: [["Достигнут лимит", "Ingress publish завершается ошибкой, producer применяет ограниченный retry. Полный result/DLQ запрещает ACK и вызывает повтор сохранения."], ["Временная ошибка", "Корректный запрос повторяется после nak_delay; после max_deliver сохраняется terminal error."], ["Дубликат", "Тот же SignedClaim имеет тот же request ID и результат."], ["Корректное завершение", "Незавершённые deliveries остаются unacked и продолжаются после restart."]],
    sdkTitle: "4. Публикация и восстановление через Go SDK",
    sdkBody: "Синхронный метод ждёт в одном вызове. Раздельные publish/wait позволяют сохранить NATSSubmission и восстановиться после disconnect или restart.",
    sdkExpected: "Accepted result содержит record_id, L2 proof_level, server record и accepted receipt. Terminal rejection возвращает *sdk.Error.",
    resumeTitle: "Правило submission handle",
    resumeBody: "Сохраняйте MessageID вместе с исходным SignedClaim и защищайте оба поля. WaitResult повторно связывает их, подписывается на точный subject и читает durable snapshot.",
    securityTitle: "5. Разделите identities и permissions",
    securityBody: "Используйте разные accounts для server и producers. Не помещайте секреты в URL. Режимы auth взаимоисключающие; TLS должен проверять CA и server name.",
    securityChecklist: ["Server: inspect topology, consume/ACK, publish result и DLQ; создание только с provision=true", "Producer: inspect ingress/result, publish только конкретный ingress subject, subscribe exact result и читать последнее сообщение", "Не нужны update/delete stream, consumer management и DLQ", "До нагрузки проверьте live wait и восстановление сохранённого результата"],
    recoveryTitle: "6. Задайте retention и recovery",
    recoveryBody: "result_max_age/result_max_bytes задают окно восстановления; по умолчанию 24h. memory намеренно нестабилен, file и replicas задают долговечность broker.",
    recoveryChecklist: ["Следить за backlog, pending/redelivery/unacked и ёмкостью result/DLQ", "Повторные worker errors исследовать в submission, broker и outcome storage", "Несовместимую topology исправлять по полям без автоматической мутации", "Настроить retention под окно восстановления приложения"],
    backupTitle: "Состояние broker не входит в .tdbackup",
    backupBody: "Ingress messages, NATS results и dead letters — транспортное состояние, не .sproof и не логический backup TrustDB. Защищайте его отдельно средствами JetStream storage и replication.",
    fullGuideLabel: "Открыть полное руководство по полям и эксплуатации",
    nextLabel: "Перейти к развёртыванию сервера",
    sdkLinkLabel: "Нужен broker-буфер? Откройте руководство NATS",
    serverLinkLabel: "Добавить необязательный JetStream ingress",
  },
  ja: {
    lang: "ja",
    updated: "2026.07.24 更新",
    version: "NATSIngressClient を含む現在の main または今後のリリース向け",
    title: "任意の NATS / JetStream 取り込み",
    lead: "署名、WAL、証明、オフライン検証の意味を変えずに、TrustDB の前へ永続バッファ、複数 producer の集約、上限付き分配を追加します。",
    duration: "20～30分",
    outcome: "既定で無効、結果を復旧でき、権限境界が明確な JetStream 書き込み経路",
    prerequisites: ["NATSIngressClient を含む TrustDB main または今後のリリース", "利用可能な NATS JetStream broker", "TrustDB が信頼する既存クライアント署名 identity", "broker account、TLS、subject 権限を設定できること"],
    boundaryTitle: "NATS が置き換えるのは書き込み transport だけで、TrustDB の証拠データベースではありません。",
    boundaryBody: "NATSIngressClient は signed claim の publish と acceptance result の復旧を担当します。records、proof export、Global Log evidence、anchor は HTTP/gRPC sdk.Client を使います。",
    ackTitle: "二つの ACK を分けて考える",
    ackBody: "JetStream と TrustDB には別々の永続境界があります。L2 を意味するのは二番目だけです。",
    ackSteps: [["01", "JetStream publish ACK", "要求は ingress stream に保存されましたが、TrustDB の検証や WAL 書き込みは未完了かもしれません。"], ["02", "TrustDB accepted result", "署名と鍵状態の検証を通過し、通常の WAL acceptance 境界 L2 を越えました。"], ["03", "ACK より先に result 保存", "server は immutable result を先に保存するため、timeout や restart 後も復旧できます。"]],
    localTitle: "1. ローカル JetStream を起動して入口を有効化",
    localBody: "以下の broker はローカル評価用です。動作済みの server、key、WAL、proofstore 設定を保ち、生成された nats セクションだけを変更します。",
    localExpected: "ログに optional NATS ingress started と ingress/result/DLQ stream、durable consumer、worker 数が表示されます。",
    localNoteTitle: "既定では無効",
    localNoteBody: "nats.enabled=false の間は broker へ接続せず、resource を確認・作成せず、HTTP/gRPC も変えません。有効化後は broker 不達や topology 不一致で起動に失敗します。",
    topologyTitle: "2. 四つの resource に役割を分ける",
    topologyBody: "provision=true は不足 resource だけを作成します。既存 resource は厳密一致が必要で、自動変更しません。infra が topology を管理する場合は false を使います。",
    topologyRows: [["Ingress stream", "trustdb.ingress.v1.claims の WorkQueue。DiscardNew と容量上限が broker backpressure を作ります。"], ["Durable consumer", "explicit ACK、正確な filter、MaxAckPending、MaxDeliver で同時実行と redelivery を制限します。"], ["Result stream", "request subject ごとに accepted または terminal error を一つだけ immutable に保存します。"], ["Dead-letter stream", "不正な subject/header/schema/message ID/CBOR を元 delivery の終了前に保存します。"]],
    flowTitle: "3. Backpressure、retry、shutdown",
    flowBody: "worker は二番目のインメモリ queue を追加しません。JetStream が broker 配布を制限し、共有 submission service は HTTP/gRPC と同じ blocking backpressure を維持します。",
    flowRows: [["容量上限", "Ingress publish は失敗し、producer は上限付き retry を行います。Result/DLQ が満杯なら ACK せず保存を再試行します。"], ["一時的失敗", "有効要求は nak_delay 後に再配信し、max_deliver 後は immutable terminal error を保存します。"], ["重複要求", "完全に同じ SignedClaim は同じ request ID と結果を使います。"], ["正常終了", "未完了 delivery は unacked のまま残り、restart 後に同じ consumer が継続します。"]],
    sdkTitle: "4. Go SDK で publish と結果復旧",
    sdkBody: "同期メソッドは一回の呼び出しで待機し、分離メソッドは publish と wait の間に NATSSubmission を保存して disconnect や restart 後に復旧します。",
    sdkExpected: "accepted result には record_id、L2 proof_level、server record、accepted receipt が含まれます。terminal rejection は *sdk.Error です。",
    resumeTitle: "Submission handle のルール",
    resumeBody: "MessageID と元の SignedClaim を一緒に保存し、変更を防ぎます。WaitResult は両者を再結合し、正確な result subject を subscribe して durable snapshot を読みます。",
    securityTitle: "5. Broker identity と権限を分離",
    securityBody: "server と producer は別 account を使い、URL に credential を入れません。auth モードは相互排他で、TLS は CA と server name を検証します。",
    securityChecklist: ["Server：topology 確認、durable consumer の consume/ACK、result/DLQ publish。作成権限は provision=true の場合だけ", "Producer：ingress/result 確認、具体 ingress subject の publish、正確な result subject の subscribe と最終結果の read", "stream 更新/削除、consumer 管理、DLQ access は不要", "トラフィック投入前に live wait と stored-result recovery の両方を試験"],
    recoveryTitle: "6. Retention と recovery 境界を決める",
    recoveryBody: "result_max_age/result_max_bytes が復旧期間を決め、既定 age は 24h です。memory は意図的に揮発性で、file と replicas が broker 耐久性を決めます。",
    recoveryChecklist: ["ingress backlog、pending/redelivery/unacked、result/DLQ 容量を監視", "反復する worker error は submission、broker、outcome storage を調査", "不一致 topology は項目ごとに修正し自動変更しない", "アプリの復旧期間に合わせて retention を設定"],
    backupTitle: "Broker 状態は .tdbackup の外",
    backupBody: "Ingress message、NATS result、dead letter は transport 状態であり、.sproof や TrustDB logical backup ではありません。JetStream storage と replication で別途保護します。",
    fullGuideLabel: "完全なフィールド・運用ガイドを見る",
    nextLabel: "サーバー導入へ進む",
    sdkLinkLabel: "Broker バッファが必要ですか？NATS ingress ガイドを見る",
    serverLinkLabel: "サービスに任意の JetStream ingress を追加",
  },
};

export function natsIngressContent(locale = "zh-CN") {
  return content[locale] || content.en;
}
